# Задание 1

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [1]:
import numpy as np
import pandas as pd

In [8]:
x = np.array ([35, 45, 190, 200, 40, 70, 54, 150, 120, 110], dtype=np.float64)
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832],  dtype=np.float64)

Коэффициенты уравнения линейной регрессии можно найти следующим образом:
$$b = \frac{\overline{yx} - \overline{y} \cdot {\overline{x}}}{\overline{x^2} - (\overline{x})^2};$$

$$a = \overline{y} - b \cdot {\overline{x}}.$$

In [9]:
b = (np.mean(x * y) - np.mean(x) * np.mean(y)) / (np.mean(x**2) - np.mean(x) ** 2)
b

2.620538882402765

In [10]:
a = np.mean(y) - b * np.mean(x)
a

444.1773573243596

Матричный метод

In [11]:
import seaborn as sns

In [12]:
x = x.reshape((10,1))
x

array([[ 35.],
       [ 45.],
       [190.],
       [200.],
       [ 40.],
       [ 70.],
       [ 54.],
       [150.],
       [120.],
       [110.]])

In [13]:
y = y.reshape ((10,1))
y

array([[401.],
       [574.],
       [874.],
       [919.],
       [459.],
       [739.],
       [653.],
       [902.],
       [746.],
       [832.]])

In [14]:
x = np.hstack([np.ones((10,1)), x])
x

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [15]:
b = np.dot(np.linalg.inv(np.dot(x.T,x)),x.T@y)
b

array([[444.17735732],
       [  2.62053888]])

# Задание 2

Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [27]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])

In [28]:
def mse_(B1,y=y,X=X,n=10):
  return np.sum((B1*X-y)**2)/n


In [29]:
alpha = 1e-6

In [30]:
B1 = 0.1
n = 10

In [35]:
for i in range (1000):
    B1 -=alpha*(2/n)*np.sum((B1*X-y)*X)
    if i%10==0:
        print('Iteration: {i}, B1={B1}, mse={mse}'.format(i=i, B1=B1, mse=mse_(B1)))  

Iteration: 0, B1=5.8898204201295625, mse=56516.85841571941
Iteration: 10, B1=5.889820420130325, mse=56516.85841571941
Iteration: 20, B1=5.8898204201309, mse=56516.8584157194
Iteration: 30, B1=5.889820420131335, mse=56516.85841571941
Iteration: 40, B1=5.889820420131667, mse=56516.8584157194
Iteration: 50, B1=5.889820420131916, mse=56516.85841571941
Iteration: 60, B1=5.8898204201321045, mse=56516.85841571943
Iteration: 70, B1=5.889820420132247, mse=56516.85841571941
Iteration: 80, B1=5.889820420132355, mse=56516.85841571941
Iteration: 90, B1=5.889820420132437, mse=56516.85841571943
Iteration: 100, B1=5.889820420132498, mse=56516.85841571941
Iteration: 110, B1=5.889820420132545, mse=56516.85841571941
Iteration: 120, B1=5.88982042013258, mse=56516.85841571943
Iteration: 130, B1=5.889820420132606, mse=56516.85841571941
Iteration: 140, B1=5.889820420132625, mse=56516.85841571939
Iteration: 150, B1=5.889820420132642, mse=56516.8584157194
Iteration: 160, B1=5.889820420132651, mse=56516.8584157

In [36]:
B1

5.889820420132673

In [40]:
mse_(5.889820420132673)

56516.85841571943